from __future__ import annotations

import hashlib
import json
import os
from datetime import datetime, timezone
from pathlib import Path, PurePosixPath
import re
import shutil
import threading
from typing import Any, Protocol
import uuid
import warnings
import zipfile

from PIL import Image, UnidentifiedImageError
from sqlalchemy import select
from sqlalchemy.exc import IntegrityError

from .conversion import atomic_json, wsl_path
from .database import CalibrationDatasetRecord, DatabaseManager


IMAGE_SUFFIXES = {".jpg", ".jpeg", ".png", ".bmp", ".webp"}
BUILTIN_DATASET_ID = "coco8-dev"
BUILTIN_YAML = "coco8.yaml"
BUILTIN_HASH = "f889fd83d2d7a73b3a4f228ff4739dccbf489e05699b98df3bd97cdcfe9f4937"
BUILTIN_SIZE_BYTES = 1_913_529


class CalibrationDatasetError(ValueError):
    pass


class Digest(Protocol):
    def update(self, data: bytes) -> None: ...


class CalibrationDatasetCatalog:
    def __init__(
        self,
        root: Path,
        database_manager: DatabaseManager | None = None,
        *,
        max_expanded_bytes: int = 2 * 1024 * 1024 * 1024,
        max_files: int = 5000,
        max_image_pixels: int = 100_000_000,
    ) -> None:
        self.root = root.resolve()
        self.assets_root = self.root / "assets"
        self.incoming_root = self.root / ".incoming"
        self.registry_path = self.root / "registry.json"
        self.database = database_manager
        self.max_expanded_bytes = max(1, int(max_expanded_bytes))
        self.max_files = max(1, int(max_files))
        self.max_image_pixels = max(1, int(max_image_pixels))
        self._guard = threading.RLock()

    @staticmethod
    def builtin() -> dict[str, Any]:
        return {
            "datasetId": BUILTIN_DATASET_ID,
            "name": "内置 8 图转换测试",
            "version": "project-v1",
            "scenario": "development-only",
            "imageCount": 8,
            "sizeBytes": BUILTIN_SIZE_BYTES,
            "contentSha256": BUILTIN_HASH,
            "yamlPath": BUILTIN_YAML,
            "builtin": True,
            "deletable": False,
            "status": "ready",
            "createdAt": None,
        }

    def prepare(self) -> None:
        self.assets_root.mkdir(parents=True, exist_ok=True)
        self.incoming_root.mkdir(parents=True, exist_ok=True)

    def incoming_path(self) -> Path:
        self.prepare()
        return self.incoming_root / f"{uuid.uuid4().hex}.zip.part"

    def list(self) -> list[dict[str, Any]]:
        custom = self._custom_records()
        custom.sort(key=lambda item: str(item.get("createdAt") or ""), reverse=True)
        return [self.builtin(), *[self._with_status(item) for item in custom]]

    def get(self, dataset_id: str) -> dict[str, Any]:
        if dataset_id == BUILTIN_DATASET_ID:
            return self.builtin()
        if not re.fullmatch(r"cal-[0-9a-f]{32}", dataset_id):
            raise KeyError(dataset_id)
        for item in self._custom_records():
            if item["datasetId"] == dataset_id:
                return self._with_status(item)
        raise KeyError(dataset_id)

    def create_from_zip(self, archive: Path, *, name: str, version: str, scenario: str) -> dict[str, Any]:
        name, version, scenario = (value.strip() for value in (name, version, scenario))
        if not name or not version or not scenario:
            raise CalibrationDatasetError("校准集名称、版本和场景不能为空")
        if any(len(value) > limit for value, limit in ((name, 100), (version, 50), (scenario, 100))):
            raise CalibrationDatasetError("校准集名称、版本或场景过长")
        if not zipfile.is_zipfile(archive):
            raise CalibrationDatasetError("请上传有效的 ZIP 图片集")

        with self._guard:
            if any(item["name"] == name and item["version"] == version for item in self._custom_records()):
                raise CalibrationDatasetError("相同名称和版本的校准集已经存在")
            self.prepare()
            dataset_id = "cal-" + uuid.uuid4().hex
            staging = self.incoming_root / (dataset_id + ".dir")
            final = self.assets_root / dataset_id
            images = staging / "images"
            images.mkdir(parents=True, exist_ok=False)
            try:
                extracted = self._extract_images(archive, images)
                yaml_bytes = (
                    "# Generated by AI YOLO calibration asset manager.\n"
                    "train: images\n"
                    "val: images\n"
                    "names:\n"
                    "  0: calibration\n"
                ).encode("utf-8")
                (staging / "dataset.yaml").write_bytes(yaml_bytes)
                digest = hashlib.sha256()
                digest.update(b"dataset.yaml\0")
                digest.update(yaml_bytes)
                total_size = len(yaml_bytes)
                for path in extracted:
                    relative = path.relative_to(staging).as_posix()
                    digest.update(relative.encode("utf-8") + b"\0")
                    total_size += self._hash_file(digest, path)
                staging.replace(final)
                payload = {
                    "datasetId": dataset_id,
                    "name": name,
                    "version": version,
                    "scenario": scenario,
                    "imageCount": len(extracted),
                    "sizeBytes": total_size,
                    "contentSha256": digest.hexdigest(),
                    "yamlPath": f"assets/{dataset_id}/dataset.yaml",
                    "builtin": False,
                    "deletable": True,
                    "createdAt": datetime.now(timezone.utc).isoformat(),
                }
                self._insert(payload)
                return self._with_status(payload)
            except BaseException:
                shutil.rmtree(staging, ignore_errors=True)
                if final.exists():
                    shutil.rmtree(final, ignore_errors=True)
                raise

    def delete(self, dataset_id: str) -> dict[str, Any]:
        if dataset_id == BUILTIN_DATASET_ID:
            raise CalibrationDatasetError("内置 coco8-dev 校准集不能删除")
        with self._guard:
            item = self.get(dataset_id)
            directory = self.assets_root / dataset_id
            tombstone = self.incoming_root / f"{dataset_id}.deleting-{uuid.uuid4().hex}"
            if directory.exists():
                directory.replace(tombstone)
            try:
                self._delete_record(dataset_id)
            except BaseException:
                if tombstone.exists():
                    tombstone.replace(directory)
                raise
            shutil.rmtree(tombstone, ignore_errors=True)
        return item

    def runtime_path(self, snapshot: dict[str, Any], mode: str) -> str:
        dataset_id = str(snapshot.get("datasetId", ""))
        current = self.get(dataset_id)
        if current["contentSha256"] != snapshot.get("contentSha256"):
            raise CalibrationDatasetError("校准集内容或版本已经变化，请重新创建转换任务")
        if current.get("status") != "ready":
            raise CalibrationDatasetError("校准集文件缺失或完整性校验失败")
        if current.get("builtin"):
            return BUILTIN_YAML
        relative = Path(str(current["yamlPath"]))
        absolute = (self.root / relative).resolve()
        digest, size, count = self._content_fingerprint(absolute.parent)
        if (
            digest != current["contentSha256"]
            or size != current["sizeBytes"]
            or count != current["imageCount"]
        ):
            raise CalibrationDatasetError("校准集文件缺失或完整性校验失败")
        if mode == "remote":
            return relative.as_posix()
        if mode == "wsl":
            return wsl_path(absolute)
        return str(absolute)

    def snapshot(self, dataset_id: str) -> dict[str, Any]:
        item = self.get(dataset_id)
        if item.get("status") != "ready":
            raise CalibrationDatasetError("校准集文件缺失或完整性校验失败")
        return {
            key: item[key]
            for key in (
                "datasetId", "name", "version", "scenario", "imageCount",
                "sizeBytes", "contentSha256", "yamlPath", "builtin",
            )
        }

    def _extract_images(self, archive: Path, destination: Path) -> list[Path]:
        output: list[Path] = []
        expanded = 0
        with zipfile.ZipFile(archive) as package:
            members = [member for member in package.infolist() if not member.is_dir()]
            if not members:
                raise CalibrationDatasetError("ZIP 中没有图片")
            if len(members) > self.max_files:
                raise CalibrationDatasetError(f"ZIP 文件数量超过上限 {self.max_files}")
            for member in members:
                normalized = member.filename.replace("\\", "/")
                path = PurePosixPath(normalized)
                if path.is_absolute() or ".." in path.parts or not path.name:
                    raise CalibrationDatasetError("ZIP 包含不安全路径")
                unix_mode = (member.external_attr >> 16) & 0xF000
                if unix_mode == 0xA000 or member.flag_bits & 0x1:
                    raise CalibrationDatasetError("ZIP 不允许符号链接或加密文件")
                if path.name in {".DS_Store", "Thumbs.db"} or "__MACOSX" in path.parts:
                    continue
                suffix = Path(path.name).suffix.lower()
                if suffix not in IMAGE_SUFFIXES:
                    raise CalibrationDatasetError(f"ZIP 只允许图片文件：{path.name}")
                expanded += member.file_size
                if expanded > self.max_expanded_bytes:
                    raise CalibrationDatasetError("ZIP 解压后大小超过限制")
                if member.file_size and (not member.compress_size or member.file_size / member.compress_size > 200):
                    raise CalibrationDatasetError("ZIP 包含异常压缩比例文件")
                target = destination / f"{len(output) + 1:06d}{suffix}"
                with package.open(member) as source, target.open("wb") as sink:
                    shutil.copyfileobj(source, sink, length=1024 * 1024)
                try:
                    with warnings.catch_warnings():
                        warnings.simplefilter("error", Image.DecompressionBombWarning)
                        with Image.open(target) as image:
                            width, height = image.size
                            if width <= 0 or height <= 0 or width * height > self.max_image_pixels:
                                raise CalibrationDatasetError(f"图片尺寸无效或过大：{path.name}")
                            image.verify()
                except (OSError, UnidentifiedImageError, Image.DecompressionBombError,
                        Image.DecompressionBombWarning) as exc:
                    raise CalibrationDatasetError(f"图片无法解析：{path.name}") from exc
                output.append(target)
        if not output:
            raise CalibrationDatasetError("ZIP 中没有可用图片")
        return output

    @staticmethod
    def _hash_file(digest: Digest, path: Path) -> int:
        size = 0
        with path.open("rb") as handle:
            for block in iter(lambda: handle.read(1024 * 1024), b""):
                digest.update(block)
                size += len(block)
        return size

    @staticmethod
    def _content_fingerprint(directory: Path) -> tuple[str, int, int]:
        yaml_path = directory / "dataset.yaml"
        images = directory / "images"
        if not yaml_path.is_file() or not images.is_dir():
            raise CalibrationDatasetError("校准集文件缺失或完整性校验失败")
        digest = hashlib.sha256()
        yaml_bytes = yaml_path.read_bytes()
        digest.update(b"dataset.yaml\0")
        digest.update(yaml_bytes)
        size = len(yaml_bytes)
        count = 0
        for path in sorted(item for item in images.iterdir() if item.is_file()):
            digest.update(f"images/{path.name}".encode("utf-8") + b"\0")
            size += CalibrationDatasetCatalog._hash_file(digest, path)
            count += 1
        return digest.hexdigest(), size, count

    def _with_status(self, item: dict[str, Any]) -> dict[str, Any]:
        result = dict(item)
        if result.get("builtin"):
            result["status"] = "ready"
            return result
        directory = self.assets_root / str(result["datasetId"])
        try:
            digest, size, count = self._content_fingerprint(directory)
            valid = (
                digest == result.get("contentSha256")
                and size == result.get("sizeBytes")
                and count == result.get("imageCount")
            )
        except (OSError, CalibrationDatasetError):
            valid = False
        result["status"] = "ready" if valid else "invalid"
        return result

    def _custom_records(self) -> list[dict[str, Any]]:
        if self.database is not None:
            with self.database.session() as session:
                rows = session.scalars(select(CalibrationDatasetRecord)).all()
                return [dict(row.payload) for row in rows]
        if not self.registry_path.is_file():
            return []
        try:
            value = json.loads(self.registry_path.read_text(encoding="utf-8"))
        except (OSError, json.JSONDecodeError) as exc:
            raise CalibrationDatasetError("校准集注册表不可用") from exc
        records = value.get("datasets", [])
        return [dict(item) for item in records if isinstance(item, dict)]

    def _insert(self, payload: dict[str, Any]) -> None:
        if self.database is not None:
            try:
                with self.database.session() as session:
                    session.add(CalibrationDatasetRecord(
                        dataset_id=payload["datasetId"],
                        name=payload["name"],
                        version=payload["version"],
                        scenario=payload["scenario"],
                        image_count=payload["imageCount"],
                        size_bytes=payload["sizeBytes"],
                        content_sha256=payload["contentSha256"],
                        yaml_path=payload["yamlPath"],
                        payload=payload,
                    ))
            except IntegrityError as exc:
                raise CalibrationDatasetError("相同名称和版本的校准集已经存在") from exc
            return
        records = self._custom_records()
        records.append(payload)
        atomic_json(self.registry_path, {"schemaVersion": 1, "datasets": records})

    def _delete_record(self, dataset_id: str) -> None:
        if self.database is not None:
            with self.database.session() as session:
                row = session.get(CalibrationDatasetRecord, dataset_id)
                if row is None:
                    raise KeyError(dataset_id)
                session.delete(row)
            return
        records = [item for item in self._custom_records() if item.get("datasetId") != dataset_id]
        atomic_json(self.registry_path, {"schemaVersion": 1, "datasets": records})
